version: '3'

services:

# API
  server:
    build: ./packages/api
    container_name: hubconfapi
    expose: 
      - 8000
    environment:
      API_HOST: "http://hubconf.thehub-aubg.com"
      APP_SERVER_PORT: 8000
    ports:
      - 8000:8000
    command: node server.js
    networks:
      - front-back

# WEB
  client:
    build: ./packages/web
    container_name: hubconfweb
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    links:
      - "server"
    command: nginx -g 'daemon off';
    volumes: 
      - ./data/certs:/etc/nginx/certs
    networks:
      - front-back

networks:
  front-back:
    driver: bridge
